### ISSUE TITLE
Name conflict: there is already a tool called diffuse

### ISSUE THREAD

**Issue by keithdtyler** [JakeWharton/dex-method-list#108]
There already exists and has existed for some time a diff tool called diffuse. 
http://diffuse.sourceforge.net/
It is a graphical tool for doing multiple-file visual diffs of text.
https://www.google.com/search?q=diffuse+software
People looking for that tool can accidentaly end up finding this tool especially since both are described as diffing tools even though they work with completely different types of files.

**Comment by JakeWharton** [comment]
I'm happy to add a little heads up to the README with a link to it. I think someone proficient enough to have the need to perform file-based diffing on anything will be able to disambiguate between the two given their one-liner descriptions.
