### ISSUE TITLE
Unable to parse line X as member mapping: # {"id":"com.android.tools.r8.synthesized"}

### ISSUE THREAD

**Issue by mateuszkwiecinski** [JakeWharton/dex-method-list#111]
After migrating the project to AGP 7.1.1 diffuse starts failing with

```
Usage: diffuse diff [OPTIONS] OLD NEW

Error: Invalid value for "--new-mapping": Unable to parse line [76] as member mapping:       # {"id":"com.android.tools.r8.synthesized"}
```

I call it via:
```
java -jar diffuse.jar diff --apk diffuse-source-file-release app/build/outputs/apk/graphql/release/app-graphql-release-unsigned.apk --old-mapping diffuse-mapping-file-release --new-mapping app/build/outputs/mapping/graphqlRelease/mapping.txt
```

here's how line 76 looks like:
![image](https://user-images.githubusercontent.com/36954793/152605137-3bb1a7ce-d7e1-4b1c-aedc-fdebd8289ef4.png)

The workaround seems to be not to pass the mapping related arguments as they are ignored either way (#96)

**Comment by JakeWharton** [comment]
Dupe of #106. Are you using the latest code? Or the latest release?

**Comment by mateuszkwiecinski** [comment]
Ah my apologies. I tried to search for an existing issue but didn't find one.
I'm using latest release 0.1.0

**Comment by JakeWharton** [comment]
For now, until I can resume regular releases, I would recommend cloning the repository and building a version from the latest codebase.
