### ISSUE TITLE
0.2.0 release

### ISSUE THREAD

**Issue by SimonMarquis** [JakeWharton/dex-method-list#151]
Hi Jake, would you mind releasing a 0.2.0 to Maven Central?
It seems like the only release dates back to Aug 27, 2020.

Personally, I'm looking for this fix:

- https://github.com/JakeWharton/diffuse/pull/121

Thanks

**Comment by JakeWharton** [comment]
https://github.com/JakeWharton/diffuse/releases/tag/0.2.0
