### ISSUE TITLE
Get origin class of method call

### ISSUE THREAD

**Issue by philipphager** [JakeWharton/dex-method-list#40]
Hey,
this is not a feature request for this repo,
but I was curious if the info in the dex code would unveil the original classes
in which the method calls were issued.
I would like to extend the tool to track if some classes reference certain methods
(to check if third-party libraries in apks reference system api calls).
Since you have more experiance with the dex bytecode format,
i wanted to ask, if this would be possible.

**Comment by JakeWharton** [comment]
The dex code contains all of the instructions of your app. You would likely have to loop through each class and then loop through each method, and then loop through the bytecodes in each method looking for the method calls. It should be doable, but I've never poked around at that depth of the format.
