### ISSUE TITLE
Factor out Dex + rendering code for library-style use?

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/dex-method-list#7]
I have a need where another tool (written in a JVM language) could use rendering of methods in a dex or apk to validate its behavior. A simple API could be teased out.

**Comment by swankjesse** [comment]
Standalone dex manipulation project? Repackage AOSP bits into the right standalone thing?

**Comment by JakeWharton** [comment]
I'm talking specifically about this library's API. Basically a static method that took a `Dex`, `InputStream`, or `byte[]` and returned a `List<String>`.
