### ISSUE TITLE
Incorrect location of binary

### ISSUE THREAD

**Issue by ansman** [JakeWharton/dex-method-list#80]
In the readme it says the binary is in `diffuse/build/diffuse` but building on `trunk` puts the binary in `diffuse/build/libs/`

**Comment by JakeWharton** [comment]
I'm releasing 0.1.0 right now. The README just updated those instructions, but they'll also be broken for about 10 more minutes.

:soon:

**Comment by ansman** [comment]
Man, is my timing bad or what haha

**Comment by JakeWharton** [comment]
You can find the latest binary attached to the latest successful GitHub Action run for now: https://github.com/JakeWharton/diffuse/actions/runs/227083994
